# Files/directories to exclude from tree visualization
excluded_from_file_tree = [
  ".nuxt",
  ".git",
  ".output",
  "node_modules",
  ".project-context.toml",
  "build",
  "dist",
  "static-site-deployment-guide.md",
  "vuetify-3-for-Nuxt.md",
]

# Files/directories to completely ignore
ignored_paths = [
  ".nuxt",
  ".output",
  "yarn.lock",
  "node_modules",
  ".git",
  ".project-context.toml",
  "build",
  "dist",
  "static-site-deployment-guide.md",
  "vuetify-3-for-Nuxt.md",
]

# Paths to include in XML content
included_paths = [
  # "README.md",
  "app.vue",
  "content/blog.md",
  # "nuxt.config.ts",
  # "package.json",
  "pages/[...slug].vue",
  "pages/index.vue",
  # "plugins/vuetify.ts",
  # "project-context.xml",
  # "public/favicon.ico",
  # "public/robots.txt",
  # "server/tsconfig.json",
  # "tsconfig.json"
]