# Files/directories to exclude from tree visualization
excluded_from_file_tree = [
  ".nuxt",
  ".git",
  ".output",
  "node_modules",
  ".project-context.toml",
  "build",
  "dist",
  "static-site-deployment-guide.md",
  "vuetify-3-for-Nuxt.md",
]

# Files/directories to completely ignore
ignored_paths = [
  ".nuxt",
  ".output",
  "yarn.lock",
  "node_modules",
  ".git",
  ".project-context.toml",
  "build",
  "dist",
  "static-site-deployment-guide.md",
  "vuetify-3-for-Nuxt.md",
]

# Paths to include in XML content
included_paths = [
  # ".DS_Store",
  # "README.md",
  "app.vue",
  "components/Benefits.vue",
  # "components/BlogCard.vue",
  # "components/BlogList.vue",
  "components/ContentTypes.vue",
  # "components/ContentTypes1.vue",
  # "components/ContentTypes2.vue",
  # "components/ContentTypes3.vue",
  "components/DemoVideo.vue",
  "components/HowItWorks.vue",
  # "components/InfinitePossibilities.vue",
  # "content/blog/content-marketing/testPost2.md",
  # "content/blog/tutorials/testPost.md",
  # "layouts/default.vue",
  # "nuxt.config.ts",
  # "package.json",
  # "pages/blog/[category]/[...slug].vue",
  # "pages/blog/[category]/index.vue",
  # "pages/blog/index.vue",
  "pages/index.vue",
  # "plugins/vuetify.ts",
  # "project-context.xml",
  # "public/.DS_Store",
  # "public/content-brief.png",
  # "public/content-type.png",
  # "public/favicon.ico",
  # "public/final-blog.png",
  # "public/final-tweet.png",
  # "public/kastor-demo-800.mp4",
  # "public/kastor-demo.mp4",
  # "public/robots.txt",
  # "public/tweet-creation.png",
  # "public/voice-creation.png",
  # "server/tsconfig.json",
  # "tsconfig.json"
]